version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "CodyCBakerPhD"
    assignees:
      - "CodyCBakerPhD"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "CodyCBakerPhD"
    assignees:
      - "CodyCBakerPhD"
