name: Chromatic (Playwright)

on: push

jobs:
    chromatic-playwright:
        name: Run Chromatic (Playwright)
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Install Playwright browsers
              run: npx playwright install chromium --with-deps
            - name: Run Playwright tests
              run: npm run test:chromatic
            - name: Run Chromatic
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_PLAYWRIGHT_PROJECT_TOKEN }}
                  playwright: true
